[project]
name = "napari_cellseg3d"
version = "0.0.2rc6"
authors = [
    {name = "Cyril Achard", email = "cyril.achard@epfl.ch"},
    {name = "Maxime Vidal", email = "maxime.vidal@epfl.ch"},
    {name = "Mackenzie Mathis", email = "mackenzie@post.harvard.edu"},
]
requires-python = ">=3.8"
dependencies = [
    "numpy",
    "napari>=0.4.14",
    "QtPy",
    "opencv-python>=4.5.5",
    "scikit-image>=0.19.2",
    "matplotlib>=3.4.1",
    "tifffile>=2022.2.9",
    "imageio-ffmpeg>=0.4.5",
    "torch>=1.11",
    "monai[nibabel,einops]>=0.9.0",
    "tqdm",
    "nibabel",
    "scikit-image",
    "pillow",
    "pyclesperanto-prototype",
    "tqdm",
    "matplotlib",
    "vispy>=0.9.6",
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]

[tool.setuptools.package-data]
"*" = ["res/*.png", "code_models/models/pretrained/*.json", "*.yaml"]

[tool.ruff]
select = [
    "E", "F", "W",
    "A",
    "B",
    "G",
    "I",
    "PT",
    "PTH",
    "RET",
    "SIM",
    "TCH",
    "NPY",
]
# Never enforce `E501` (line length violations) and 'E741' (ambiguous variable names)
# and 'G004' (do not use f-strings in logging)
ignore = ["E501", "E741", "G004", "A003"]
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
    "docs/conf.py",
    "napari_cellseg3d/_tests/conftest.py",
]

[tool.black]
line-length = 79

[tool.isort]
profile = "black"
line_length = 79

[project.optional-dependencies]
all = [
    "napari[all]>=0.4.14",
]
dev = [
    "isort",
    "black",
    "ruff",
    "tuna",
    "pre-commit",

]
docs = [
    "sphinx",
    "sphinx_autodoc_typehints",
    "sphinx_rtd_theme",
    "twine",
]
test = [
    "pytest",
    "pytest_qt",
    "coverage",
    "tox",
    "twine",
]

