[project]
name = "napari_cellseg3d"
version = "0.0.2rc2"
authors = [
    {name = "Cyril Achard", email = "cyril.achard@epfl.ch"},
    {name = "Maxime Vidal", email = "maxime.vidal@epfl.ch"},
    {name = "Mackenzie Mathis", email = "mackenzie@post.harvard.edu"},
]
requires-python = ">=3.8"
dependencies = [
    "numpy",
    "napari[all]>=0.4.14",
    "QtPy",
    "opencv-python>=4.5.5",
    "dask-image>=0.6.0",
    "scikit-image>=0.19.2",
    "matplotlib>=3.4.1",
    "tifffile>=2022.2.9",
    "imageio-ffmpeg>=0.4.5",
    "torch>=1.11",
    "monai[nibabel,einops]>=0.9.0",
    "itk",
    "tqdm",
    "nibabel",
    "scikit-image",
    "pillow",
    "tqdm",
    "matplotlib",
    "vispy>=0.9.6",
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.ruff]
# Never enforce `E501` (line length violations).
ignore = ["E501", "E741"]

[tool.black]
line-length = 79

[tool.isort]
profile = "black"
line_length = 79

[project.optional-dependencies]
dev = [
    "isort",
    "black",
    "ruff",
]
docs = [
    "sphinx",
    "sphinx_autodoc_typehints",
    "sphinx_rtd_theme",
    "twine",
]
test = [
    "pytest",
    "pytest_qt",
    "coverage",
    "tox",
    "twine",
]