[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.ruff]
# Never enforce `E501` (line length violations).
ignore = ["E501"]

[tool.black]
line-length = 79

[tool.isort]
profile = "black"
line_length = 79

[project.optional-dependencies]
dev = [
    "isort",
    "black",
    "ruff",
]
docs = [
    "sphinx",
    "sphinx-autodoc-typehints",
    "sphinx-rtd-theme",
    "twine",
]
test = [
    "pytest",
    "pytest-qt",
    "coverage",
    "tox",
    "twine",
]