# For more information about tox, see https://tox.readthedocs.io/en/latest/
[tox]
envlist = py{310,311,312}-{linux,windows,macos}
isolated_build=true

[gh-actions]
python =
    3.10: py310
    3.11: py311
    3.12: py312

[gh-actions:env]
PLATFORM =
    ubuntu-latest: linux
    windows-latest: windows
    macos-latest: macos

[testenv]
platform =
    linux: linux
    windows: win32
    macos: darwin
passenv =
    CI
    PYTHONPATH
    GITHUB_ACTIONS
    DISPLAY
    XAUTHORITY
    NUMPY_EXPERIMENTAL_ARRAY_FUNCTION
    PYVISTA_OFF_SCREEN

    windows: USERNAME = runneradmin
    windows: TORCHINDUCTOR_CACHE_DIR = {envtmpdir}/torchinductor

extras = test,crf,pyqt6
usedevelop = true
commands = pytest -v --color=yes --cov=napari_cellseg3d --cov-report=xml
