visibility: public
# note : remember to add napari-hub preview app to repo

project_urls:
  Bug Tracker: https://github.com/AdaptiveMotorControlLab/CellSeg3D/issues
  Documentation: https://adaptivemotorcontrollab.github.io/CellSeg3D/res/welcome.html
  Source Code: https://github.com/AdaptiveMotorControlLab/CellSeg3D
  Project Site: https://github.com/AdaptiveMotorControlLab/CellSeg3D
  User Support: https://github.com/AdaptiveMotorControlLab/CellSeg3D/issues

# Add labels from the EDAM Bioimaging ontology
labels:
  ontology: EDAM-BIOIMAGING:alpha06
  terms:
  - 3D image
  - Cell segmentation
  - Light-sheet microscopy
  - Image visualisation
  - Neuron image analysis
  - Convolutional neural network
  - Watershed segmentation
  - Object counting
  - Image crop
  - Plotting
