name: build_docs

# execute this workflow automatically when we push to master
on:
  push:
    branches: [ main ]

jobs:

  build_docs:
    runs-on: ubuntu-latest
    container: debian:buster-slim

    steps:
      - uses: actions/checkout@v2

      - name: Prereqs
        env:
          GITHUB_TOKEN: ${{ secrets.CREATE_DEMO_SECRET }}
        run: |
          set -x
          apt-get update
          apt-get install -y git
          git clone "https://token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" .
        shell: bash

      - name: Run build script for Sphinx pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: "docs/buildsite.sh"
        shell: bash





